name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get install -q gcc make libfftw3-dev liblapacke-dev libpng-dev libopenblas-dev gfortran
    - name: make all
      run: make all
    - name: make utest
      run: make utest
    - name: make test
      run: make test
    - name: make pythontest
      run: |
        sudo apt-get install -q python3 python3-numpy
        make pythontest
